name = "cdn"
main = "src/index.ts"
compatibility_date = "2023-03-07"
send_metrics = false

account_id = "e92671ee3f768626ba9247b935e077d4"
workers_dev = false

routes = [
    "cdn.serenmodz.rocks/*",
    "cdn.ghosty.link/*",
    "cdn.demonyuto.link/*"
]

kv_namespaces = [
    { binding = "CDN_USERS", id = "c43452a3e71a4681a00cc14edcc9d4fa", preview_id = "c5d67610a03b481c8822f529d74ad7a1" }
]

[[r2_buckets]]
binding = "CDN_BUCKET"
bucket_name = "cdn"
preview_bucket_name = "cdn"

[vars]
REDIRECT_URL = "https://www.serenmodz.rocks"
